package cz.mg.resampler.gui.components.export;

import cz.mg.resampler.gui.dialogs.ImageFileDialog;
import cz.mg.resampler.gui.utilities.ImageUtilities;


public class FileChooserPanel extends javax.swing.JPanel {
    public FileChooserPanel() {
        initComponents();
    }
    
    public String getFilePath(){
        return jTextFieldPath.getText();
    }
    
    public ImageUtilities.ImageFileFormat getFileFormat(){
        return ImageUtilities.ImageFileFormat.fromString((String) jComboBoxFormat.getSelectedItem());
    }
    
    private void chooseFile(){
        String path = ImageFileDialog.savePath(this);
        if(path != null) jTextFieldPath.setText(path);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelFile = new javax.swing.JLabel();
        jTextFieldPath = new javax.swing.JTextField();
        jComboBoxFormat = new javax.swing.JComboBox<>();
        jButtonChooseFile = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWeights = new double[] {0.0, 1.0, 0.0, 0.0};
        setLayout(layout);

        jLabelFile.setText("File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        add(jLabelFile, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(jTextFieldPath, gridBagConstraints);

        jComboBoxFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PNG", "JPG", "BMP" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(jComboBoxFormat, gridBagConstraints);

        jButtonChooseFile.setText("...");
        jButtonChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseFileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(jButtonChooseFile, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseFileActionPerformed
        chooseFile();
    }//GEN-LAST:event_jButtonChooseFileActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChooseFile;
    private javax.swing.JComboBox<String> jComboBoxFormat;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables
}
