package cz.mg.resampler.gui.components.export;

import cz.mg.resampler.gui.utilities.NumberUtilities;


public class ImageSizeChooserPanel extends javax.swing.JPanel {
    public ImageSizeChooserPanel() {
        initComponents();
    }
    
    public void setTitle(String title){
        jLabelTitle.setText(title);
    }

    public int getImageWidth() {
        return NumberUtilities.toInteger(jSpinnerW.getValue());
    }

    public void setImageWidth(int width) {
        jSpinnerW.setValue(width);
    }

    public int getImageHeight() {
        return NumberUtilities.toInteger(jSpinnerH.getValue());
    }

    public void setImageHeight(int height) {
        jSpinnerH.setValue(height);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTitle = new javax.swing.JLabel();
        jLabelW = new javax.swing.JLabel();
        jLabelH = new javax.swing.JLabel();
        jSpinnerW = new javax.swing.JSpinner();
        jSpinnerH = new javax.swing.JSpinner();

        setLayout(new java.awt.GridBagLayout());

        jLabelTitle.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        add(jLabelTitle, gridBagConstraints);

        jLabelW.setText("Width:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabelW, gridBagConstraints);

        jLabelH.setText("Height:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(jLabelH, gridBagConstraints);

        jSpinnerW.setMinimumSize(new java.awt.Dimension(64, 20));
        jSpinnerW.setPreferredSize(new java.awt.Dimension(64, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(jSpinnerW, gridBagConstraints);

        jSpinnerH.setMinimumSize(new java.awt.Dimension(64, 20));
        jSpinnerH.setPreferredSize(new java.awt.Dimension(64, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(jSpinnerH, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelH;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelW;
    private javax.swing.JSpinner jSpinnerH;
    private javax.swing.JSpinner jSpinnerW;
    // End of variables declaration//GEN-END:variables
}
