package cz.mg.resampler.gui.components.export;


public class ImageSizeLabelsPanel extends javax.swing.JPanel {
    private int imageWidth = 0;
    private int imageHeight = 0;
    
    public ImageSizeLabelsPanel() {
        initComponents();
    }
    
    public void setTitle(String title){
        jLabelTitle.setText(title);
    }

    public void setImageWidth(int imageWidth) {
        this.imageWidth = imageWidth;
        jLabelWV.setText("" + imageWidth);
    }

    public void setImageHeight(int imageHeight) {
        this.imageHeight = imageHeight;
        jLabelHV.setText("" + imageHeight);
    }

    public int getImageWidth() {
        return imageWidth;
    }

    public int getImageHeight() {
        return imageHeight;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTitle = new javax.swing.JLabel();
        jLabelW = new javax.swing.JLabel();
        jLabelH = new javax.swing.JLabel();
        jLabelWV = new javax.swing.JLabel();
        jLabelHV = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabelTitle.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        add(jLabelTitle, gridBagConstraints);

        jLabelW.setText("Width:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabelW, gridBagConstraints);

        jLabelH.setText("Height:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(jLabelH, gridBagConstraints);

        jLabelWV.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(jLabelWV, gridBagConstraints);

        jLabelHV.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(jLabelHV, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelH;
    private javax.swing.JLabel jLabelHV;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelW;
    private javax.swing.JLabel jLabelWV;
    // End of variables declaration//GEN-END:variables
}
