package cz.mg.resampler.gui.components.export;

import cz.mg.resampler.gui.utilities.NumberUtilities;
import cz.mg.resampler.resamplers.java.utilities.IntegerRegion;


public class IntegerRegionChooserPanel extends javax.swing.JPanel {
    public IntegerRegionChooserPanel() {
        initComponents();
        jCheckBoxFullImage.setSelected(true);
        updateLocks();
    }
    
    public void setTitle(String title){
        jLabelTitle.setText(title);
    }
    
    public IntegerRegion getRegion(){
        if(isFullImage()) return null;
        return new IntegerRegion(
                NumberUtilities.toInteger(jSpinnerX.getValue()),
                NumberUtilities.toInteger(jSpinnerY.getValue()),
                NumberUtilities.toInteger(jSpinnerW.getValue()),
                NumberUtilities.toInteger(jSpinnerH.getValue())
        );
    }
    
    public void setRegion(IntegerRegion region){
        jSpinnerX.setValue(region.getX());
        jSpinnerY.setValue(region.getY());
        jSpinnerW.setValue(region.getWidth());
        jSpinnerH.setValue(region.getHeight());
    }
    
    private boolean isFullImage(){
        return jCheckBoxFullImage.isSelected();
    }
    
    private void updateLocks(){
        boolean enabled = !isFullImage();
        jLabelX.setEnabled(enabled);
        jLabelY.setEnabled(enabled);
        jLabelW.setEnabled(enabled);
        jLabelH.setEnabled(enabled);
        jSpinnerX.setEnabled(enabled);
        jSpinnerY.setEnabled(enabled);
        jSpinnerW.setEnabled(enabled);
        jSpinnerH.setEnabled(enabled);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jCheckBoxFullImage = new javax.swing.JCheckBox();
        jLabelX = new javax.swing.JLabel();
        jLabelY = new javax.swing.JLabel();
        jLabelW = new javax.swing.JLabel();
        jLabelH = new javax.swing.JLabel();
        jSpinnerX = new javax.swing.JSpinner();
        jSpinnerY = new javax.swing.JSpinner();
        jSpinnerW = new javax.swing.JSpinner();
        jSpinnerH = new javax.swing.JSpinner();

        jLabel3.setText("jLabel3");

        setLayout(new java.awt.GridBagLayout());

        jPanelHeader.setLayout(new java.awt.GridBagLayout());

        jLabelTitle.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        jPanelHeader.add(jLabelTitle, gridBagConstraints);

        jCheckBoxFullImage.setText("Full image");
        jCheckBoxFullImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFullImageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        jPanelHeader.add(jCheckBoxFullImage, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jPanelHeader, gridBagConstraints);

        jLabelX.setText("X:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabelX, gridBagConstraints);

        jLabelY.setText("Y:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(jLabelY, gridBagConstraints);

        jLabelW.setText("Width:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(jLabelW, gridBagConstraints);

        jLabelH.setText("Height:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(jLabelH, gridBagConstraints);

        jSpinnerX.setModel(new javax.swing.SpinnerNumberModel());
        jSpinnerX.setMinimumSize(new java.awt.Dimension(64, 20));
        jSpinnerX.setPreferredSize(new java.awt.Dimension(64, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(jSpinnerX, gridBagConstraints);

        jSpinnerY.setModel(new javax.swing.SpinnerNumberModel());
        jSpinnerY.setMinimumSize(new java.awt.Dimension(64, 20));
        jSpinnerY.setPreferredSize(new java.awt.Dimension(64, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(jSpinnerY, gridBagConstraints);

        jSpinnerW.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerW.setMinimumSize(new java.awt.Dimension(64, 20));
        jSpinnerW.setPreferredSize(new java.awt.Dimension(64, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(jSpinnerW, gridBagConstraints);

        jSpinnerH.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerH.setMinimumSize(new java.awt.Dimension(64, 20));
        jSpinnerH.setPreferredSize(new java.awt.Dimension(64, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(jSpinnerH, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxFullImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFullImageActionPerformed
        updateLocks();
    }//GEN-LAST:event_jCheckBoxFullImageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxFullImage;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelH;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelW;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JSpinner jSpinnerH;
    private javax.swing.JSpinner jSpinnerW;
    private javax.swing.JSpinner jSpinnerX;
    private javax.swing.JSpinner jSpinnerY;
    // End of variables declaration//GEN-END:variables
}
