package cz.mg.resampler.gui.components;

import cz.mg.resampler.gui.components.configuration.ParametersPanel;
import cz.mg.resampler.gui.state.ResamplerConfiguration;
import javax.swing.event.ChangeListener;


public class ResamplerConfigurationPanel extends javax.swing.JPanel {
    private final ResamplerConfiguration resamplerConfiguration = new ResamplerConfiguration();
    private final ParametersPanel parametersPanel;

    public ResamplerConfigurationPanel(String name) {
        initComponents();
        jLabelTitle.setText(name);
        parametersPanel = new ParametersPanel(resamplerConfiguration, name);
        jPanelParametersWrap.add(parametersPanel);
    }

    public ResamplerConfiguration getResamplerConfiguration() {
        return resamplerConfiguration;
    }
    
    public void addChangeListener(ChangeListener changeListener){
        parametersPanel.addChangeListener(changeListener);
    }
    
    public void removeChangeListener(ChangeListener changeListener){
        parametersPanel.removeChangeListener(changeListener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTitle = new javax.swing.JLabel();
        jPanelParametersWrap = new javax.swing.JPanel();
        jPanelVerticalSpacer = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWeights = new double[] {1.0};
        layout.rowWeights = new double[] {0.0, 0.0, 1.0};
        setLayout(layout);

        jLabelTitle.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 2, 4);
        add(jLabelTitle, gridBagConstraints);

        jPanelParametersWrap.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelParametersWrap.setLayout(new java.awt.GridLayout(1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 4, 4);
        add(jPanelParametersWrap, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanelVerticalSpacer, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelParametersWrap;
    private javax.swing.JPanel jPanelVerticalSpacer;
    // End of variables declaration//GEN-END:variables
}
