package cz.mg.resampler.gui.components;

import cz.mg.resampler.gui.MainWindow;
import cz.mg.resampler.gui.utilities.ImageState;
import cz.mg.resampler.gui.utilities.View;
import java.text.DecimalFormat;


public class StatusBar extends javax.swing.JPanel {
    private final DecimalFormat decimalFormat = new DecimalFormat("0.000");
    private final MainWindow myParent;

    public StatusBar(MainWindow myParent) {
        this.myParent = myParent;
        initComponents();
    }
    
    private boolean check(){
        ImageState image = myParent.getImage();
        if(image == null){
            hideInformation();
            return false;
        } else {
            showInformation();
            return true;
        }
    }
    
    public void update(Integer mx, Integer my){
        updateImageLabels();
        updateViewLabels();
        if(mx != null && my != null) updateMouseLabels(mx, my);
    }
    
    private void updateImageLabels(){
        if(!check()) return;
        ImageState image = myParent.getImage();
        jLabelImageSize.setText(image.getWidth() + " x " + image.getHeight());
    }
    
    private void updateViewLabels(){
        if(!check()) return;
        View view = myParent.getView();
        float sx = myParent.getView().getRx() * myParent.getImage().getWidth();
        float sy = myParent.getView().getRy() * myParent.getImage().getHeight();
        jLabelViewZoom.setText(decimalFormat.format(view.getZoom()));
        jLabelViewPosition.setText("x: " + decimalFormat.format(sx) + "  y: " + decimalFormat.format(sy));
    }
    
    private void updateMouseLabels(int mx, int my){
        if(!check()) return;
        showMouseLabels();
        View view = myParent.getView();
        float sx = view.destinationToSourceX_I2F(mx);
        float sy = view.destinationToSourceY_I2F(my);
        jLabelMousePosition.setText("x: " + decimalFormat.format(sx) + "  y: " + decimalFormat.format(sy));
    }
    
    public void hideInformation(){
        hideImageLabels();
        hideViewLabels();
        hideMouseLabels();
        showNoImageLabels();
    }
    
    public void showInformation(){
        showImageLabels();
        showViewLabels();
        hideNoImageLabels();
    }
    
    public void hideNoImageLabels(){
        jLabelNoImage.setVisible(false);
    }
    
    public void hideImageLabels(){
        jLabelImageSizeHeader.setVisible(false);
        jLabelImageSize.setVisible(false);
    }
    
    public void hideViewLabels(){
        jLabelViewZoomHeader.setVisible(false);
        jLabelViewZoom.setVisible(false);
        jLabelViewPositionHeader.setVisible(false);
        jLabelViewPosition.setVisible(false);
    }
    
    public void hideMouseLabels(){
        jLabelMousePositionHeader.setVisible(false);
        jLabelMousePosition.setVisible(false);
    }
    
    public void showNoImageLabels(){
        jLabelNoImage.setVisible(true);
    }
    
    public void showImageLabels(){
        jLabelImageSizeHeader.setVisible(true);
        jLabelImageSize.setVisible(true);
    }
    
    public void showViewLabels(){
        jLabelViewZoomHeader.setVisible(true);
        jLabelViewZoom.setVisible(true);
        jLabelViewPositionHeader.setVisible(true);
        jLabelViewPosition.setVisible(true);
    }
    
    public void showMouseLabels(){
        jLabelMousePositionHeader.setVisible(true);
        jLabelMousePosition.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelImageSizeHeader = new javax.swing.JLabel();
        jLabelImageSize = new javax.swing.JLabel();
        jLabelViewZoomHeader = new javax.swing.JLabel();
        jLabelViewZoom = new javax.swing.JLabel();
        jLabelViewPositionHeader = new javax.swing.JLabel();
        jLabelViewPosition = new javax.swing.JLabel();
        jLabelMousePositionHeader = new javax.swing.JLabel();
        jLabelMousePosition = new javax.swing.JLabel();
        jLabelNoImage = new javax.swing.JLabel();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.rowWeights = new double[] {0.0};
        setLayout(layout);

        jLabelImageSizeHeader.setText("Image size:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        add(jLabelImageSizeHeader, gridBagConstraints);

        jLabelImageSize.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        add(jLabelImageSize, gridBagConstraints);

        jLabelViewZoomHeader.setText("View zoom:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 2);
        add(jLabelViewZoomHeader, gridBagConstraints);

        jLabelViewZoom.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        add(jLabelViewZoom, gridBagConstraints);

        jLabelViewPositionHeader.setText("View position:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 2);
        add(jLabelViewPositionHeader, gridBagConstraints);

        jLabelViewPosition.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        add(jLabelViewPosition, gridBagConstraints);

        jLabelMousePositionHeader.setText("Mouse position:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 2);
        add(jLabelMousePositionHeader, gridBagConstraints);

        jLabelMousePosition.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 4);
        add(jLabelMousePosition, gridBagConstraints);

        jLabelNoImage.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jLabelNoImage, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImageSize;
    private javax.swing.JLabel jLabelImageSizeHeader;
    private javax.swing.JLabel jLabelMousePosition;
    private javax.swing.JLabel jLabelMousePositionHeader;
    private javax.swing.JLabel jLabelNoImage;
    private javax.swing.JLabel jLabelViewPosition;
    private javax.swing.JLabel jLabelViewPositionHeader;
    private javax.swing.JLabel jLabelViewZoom;
    private javax.swing.JLabel jLabelViewZoomHeader;
    // End of variables declaration//GEN-END:variables
}
