package cz.mg.resampler.gui.components.value;

import cz.mg.resampler.gui.utilities.ValueObservable;
import java.util.LinkedList;
import java.util.List;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;


public class BooleanValuePanel extends javax.swing.JPanel implements ValueObservable {
    private boolean defaultValue;
    private List<ChangeListener> changeListeners = new LinkedList<>();
    
    public BooleanValuePanel() {
        initComponents();
        postInitComponents();
    }
    
    private void postInitComponents(){
        setComponentPopupMenu(jPopupMenu);
        jCheckBox.setInheritsPopupMenu(true);
    }

    public boolean isDefaultValue() {
        return defaultValue;
    }

    public void setDefaultValue(boolean defaultValue) {
        this.defaultValue = defaultValue;
    }
    
    public String getTitle(){
        return jCheckBox.getText();
    }
    
    public void setTitle(String title){
        jCheckBox.setText(title);
    }
    
    public boolean getValue(){
        return jCheckBox.isSelected();
    }
    
    public void setValue(boolean value){
        jCheckBox.setSelected(value);
    }
    
    @Override
    public void addChangeListener(ChangeListener listener){
        changeListeners.add(listener);
    }
    
    @Override
    public void removeChangeListener(ChangeListener listener){
        changeListeners.remove(listener);
    }
    
    public void reset(){
        setValue(defaultValue);
    }
    
    private void checkBoxClicked(){
        for(ChangeListener l : changeListeners) l.stateChanged(new ChangeEvent(this));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuItemReset = new javax.swing.JMenuItem();
        jCheckBox = new javax.swing.JCheckBox();

        jMenuItemReset.setText("Reset");
        jMenuItemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemResetActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemReset);

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWeights = new double[] {1.0};
        layout.rowWeights = new double[] {0.0};
        setLayout(layout);

        jCheckBox.setText("N/A");
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jCheckBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemResetActionPerformed
        reset();
    }//GEN-LAST:event_jMenuItemResetActionPerformed

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        checkBoxClicked();
    }//GEN-LAST:event_jCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JMenuItem jMenuItemReset;
    private javax.swing.JPopupMenu jPopupMenu;
    // End of variables declaration//GEN-END:variables
}
