package cz.mg.resampler.gui.dialogs;

import javax.swing.JFrame;


public class ErrorLogDialog extends javax.swing.JDialog {
    private static ErrorLogDialog logDialog = null;
    private static String log = "";
    
    public static void show(JFrame parent){
        if(logDialog == null) logDialog = new ErrorLogDialog(parent);
        logDialog.jTextArea.setText(log);
        logDialog.setVisible(true);
        logDialog.setLocationRelativeTo(null);
    }
    
    private ErrorLogDialog(JFrame parent) {
        super(parent, false);
        initComponents();
        jTextArea.setText(log);
    }
    
    public static void log(String log){
        logDialog.log = log;
        if(logDialog != null) logDialog.jTextArea.setText(log);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Error log");
        setPreferredSize(new java.awt.Dimension(640, 480));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWeights = new double[] {1.0};
        layout.rowWeights = new double[] {1.0};
        getContentPane().setLayout(layout);

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane.setViewportView(jTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(jScrollPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
